# -*- coding: utf-8 -*-
"""Graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qW_0V_cvzSIm5b2UACx282UsX_BY94aC
"""

""" Graph Representation
"""
# Array of Edges (Directed) [Start, End]

A = [[0,1], [1,2], [0,3], [3,4], [3,6], [3,7], [4,2], [4,5], [5,2]]
A

# Converting array to adjacency matrix

M = []
n = len(A)
for i in range(n):
  M.append([0]*n)

# Nodes pointing on to a connection
for u, v in A:
  M[u][v] = 1
  # M[v][u] = 1
M

# Converting array of edges to Adjacency List

from collections import defaultdict

D = defaultdict(list)

for u, v in A:
  D[u].append(v)
  # if the graph is undirected:
  # D[v].append(u)

D, D[3]

# DFS with Recursion - O(V+E) time, O(V) space, where V is the number of nodes and E is the number of edges

"""
We start out search out from 0. We need a seen set that is global to the function and we'll say that we've already seen the source. We'll also write a recursive function, where the node is the source.

"""

def dfs_recursive(node):
  print(node)
  for nei_node in D[node]:
    if nei_node not in seen:
      seen.add(nei_node)
      dfs_recursive(nei_node)

source = 0
seen = set()
seen.add(source)
dfs_recursive(source)

# Iterarive DFS with stack - O(V+E)

source = 0
seen = set()
seen.add(source)
stack = [source]

while stack:
  node = stack.pop()
  print(node)
  for nei_node in D[node]:
    if nei_node not in seen:
      seen.add(nei_node)
      stack.append(nei_node)

# BFS (Queue) - O(V+E)
# very similar to the stack but you just pop from left

from collections import deque

source = 0
seen = set()
seen.add(source)
q = deque()
q.append(source)

while q:
  node = q.popleft()
  print(node)
  for nei_node in D[node]:
    if nei_node not in seen:
      seen.add(nei_node)
      q.append(nei_node)

# Building an Adjacency List

def buildGraph(n, edges, directed = False):
  adj = defaultdict(list)
  for u, v in edges:
    adj[u].append(v)
    if not directed:
      adj[v].append(u)
  return adj

"""## Union Find"""

# Disjoint Set Union, DSU
"""
Your goal is to quickly answer two questions:
Find: who is the "Ultimate Leader" of Person A's club?
Union: Can you make Person A and Person B's clubs merge into one?
Two arrays : parent[i] -> parent pointer
rank[i] -> tree height or size

Initially, everyone is their own boss....parent[i] = i, rank[i] = 0
"""

"""
Trees should stay almost flat...so combined with path compression, find ~ O(1) and union ~ O(1), even for millions of node
Union find always tries: small tree -> attach -> big tree and never big tree -> attach -> small tree
this keeps the depth minimal

When to reach for Union-Find:
If you see these phrases in a LeetCode prompt, ignore BFS/DFS and use Union-Find:
"Find the number of connected components."
"Are these two nodes connected?"
"Detect a cycle in an undirected graph."
"Redundant Connection."
"Earliest moment everyone became friends."
"""


class UnionFind:
  def __init__(self, n):
    self.parent = [i for i in range(n)]
    self.rank = [0]*n

  def find(self, x):
    if self.parent[x] != x:
      self.parent[x] = self.find(self.parent[x]) # Path compression
    return self.parent[x]

  def union(self, a, b):
    rootA = self.find(a)
    rootB = self.find(b)

    if rootA == rootB:
      return False # Already in the same set

    # Union by rank: attach smaller rank tree under root of higher rank tree
    if self.rank[rootA] > self.rank[rootB]:
      self.parent[rootB] = rootA
    elif self.rank[rootA] < self.rank[rootB]:
      self.parent[rootA] = rootB
    else: # Ranks are equal, choose one as root and increment its rank
      self.parent[rootB] = rootA
      self.rank[rootA] += 1
    return True

"""### Example Usage of UnionFind"""

# Initialize UnionFind for 5 elements (0 to 4)
uf = UnionFind(5)
print(f"Initial parent array: {uf.parent}")

# Perform some union operations
print("\nPerforming union operations:")
uf.union(0, 1) # Union 0 and 1
print(f"After union(0,1): parent = {uf.parent}, rank = {uf.rank}")
uf.union(1, 2) # Union 1 and 2 (0, 1, 2 are now connected)
print(f"After union(1,2): parent = {uf.parent}, rank = {uf.rank}")
uf.union(3, 4) # Union 3 and 4
print(f"After union(3,4): parent = {uf.parent}, rank = {uf.rank}")
uf.union(0, 4) # Union 0 and 4 (all elements 0-4 are now connected)
print(f"After union(0,4): parent = {uf.parent}, rank = {uf.rank}")

# Check if elements are connected using find
print("\nChecking connections with find:")
print(f"Are 0 and 2 connected? {uf.find(0) == uf.find(2)}")
print(f"Are 1 and 3 connected? {uf.find(1) == uf.find(3)}")
print(f"Are 0 and 4 connected? {uf.find(0) == uf.find(4)}")

# Try to union elements already in the same set
print("\nAttempting to union 0 and 1 again:")
print(f"Union(0,1) result: {uf.union(0, 1)}")
print(f"Parent array after re-union(0,1): {uf.parent}")

# Number of Connected Components in an Undirected Graph
# for each of the nodes in the edges, see if they form a union....if they do then there is a path between them so the count decrements.

class connectedComponents:
  def __init__(self, n, edges):
    self.parent = [i for i in range(n)]
    self.rank = [1]*n

    for u, v in edges:
      if self.union(u, v):
        count -= 1
    return count

  def numberOfConnected(self, a, b, n):
    count = n

  def find(self, x):
    if self.parent[x] != x:
      self.parent[x] = self.find(self.parent[x])
    return self.parent[x]

  def union(self, a, b):
    rootA = self.find[a]
    rootB = self.find[b]

    if rootA == rootB:
      return False

    if self.rank[rootA] > self.rank[rootB]:
      self.parent[rootB] = rootA
    elif self.rank[rootB] > self.rank[rootA]:
      self.parent[rootA] = rootB
    else:
      self.parent[rootB] = rootA
      self.rank[rootA] += 1
    return True

class UnionFind:
  def __init__(self, n):
    self.parent = [i for i in range(n)]
    self.rank = [1] * n
    self.components = n

  def find(self, x):
    if self.parent[x] != x:
      self.parent[x] = self.find(self.parent[x])
    return self.parent[x]

  def union(self, a, b):
    rootA = self.parent[a]
    rootB = self.parent[b]

    if rootA == rootB: return False

    if self.rank[rootA] > self.rank[rootB]:
      self.parent[rootB] = rootA
    elif self.rank[rootB] > self.rank[rootA]:
      self.parent[rootA] = rootB
    else:
      self.parent[rootB] = rootA
      self.rank[rootA] += 1

    self.components -= 1
    return True



def countComponents(n, edges):
  uf = UnionFind(n)
  # count = n
  for u, v in edges:
    uf.union(u, v)
    # count -= 1      # this can also be done
  # return count

  return uf.components


def graphValidTree()

n1 = 5
e1 = [[0,1],[1,2],[3,4]]
result1 = countComponents(n1, e1)
print(result1)

# Test 2: fully connected → 1
n2 = 5
e2 = [[0,1],[1,2],[2,3],[3,4]]
result2 = countComponents(n2, e2)
print(result2)

