# -*- coding: utf-8 -*-
"""Graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qW_0V_cvzSIm5b2UACx282UsX_BY94aC
"""

""" Graph Representation
"""
# Array of Edges (Directed) [Start, End]

A = [[0,1], [1,2], [0,3], [3,4], [3,6], [3,7], [4,2], [4,5], [5,2]]
A

# Converting array to adjacency matrix

M = []
n = len(A)
for i in range(n):
  M.append([0]*n)

# Nodes pointing on to a connection
for u, v in A:
  M[u][v] = 1
  # M[v][u] = 1
M

# Converting array of edges to Adjacency List

from collections import defaultdict

D = defaultdict(list)

for u, v in A:
  D[u].append(v)
  # if the graph is undirected:
  # D[v].append(u)

D, D[3]

# DFS with Recursion - O(V+E) time, O(V) space, where V is the number of nodes and E is the number of edges

"""
We start out search out from 0. We need a seen set that is global to the function and we'll say that we've already seen the source. We'll also write a recursive function, where the node is the source.

"""

def dfs_recursive(node):
  print(node)
  for nei_node in D[node]:
    if nei_node not in seen:
      seen.add(nei_node)
      dfs_recursive(nei_node)

source = 0
seen = set()
seen.add(source)
dfs_recursive(source)

# Iterarive DFS with stack - O(V+E)

source = 0
seen = set()
seen.add(source)
stack = [source]

while stack:
  node = stack.pop()
  print(node)
  for nei_node in D[node]:
    if nei_node not in seen:
      seen.add(nei_node)
      stack.append(nei_node)

# BFS (Queue) - O(V+E)
# very similar to the stack but you just pop from left

from collections import deque

source = 0
seen = set()
seen.add(source)
q = deque()
q.append(source)

while q:
  node = q.popleft()
  print(node)
  for nei_node in D[node]:
    if nei_node not in seen:
      seen.add(nei_node)
      q.append(nei_node)

# Building an Adjacency List

def buildGraph(n, edges, directed = False):
  adj = defaultdict(list)
  for u, v in edges:
    adj[u].append(v)
    if not directed:
      adj[v].append(u)
  return adj

"""## Union Find"""

# Disjoint Set Union, DSU
"""
Your goal is to quickly answer two questions:
Find: who is the "Ultimate Leader" of Person A's club?
Union: Can you make Person A and Person B's clubs merge into one?
Two arrays : parent[i] -> parent pointer
rank[i] -> tree height or size

Initially, everyone is their own boss....parent[i] = i, rank[i] = 0
"""


class UnionFind:
  def __init__(self, n):
    self.parent = [i for i in range(n)]
    self.rank = [0]*n

    def find(self, x):
      if parent[x] != x:
        parent[x] = find(parent[x])
      return parent[x]

    def union(self, a, b):
      rootA = find(a)
      rootB = find(b)

      if rootA == rootB:
        return False

      if rank[rootA] > rank[rootB]:
        parent[rootB] = rootA
      elif rank[rootB] > rank[rootA]:
        parent[rootA] = rootB
      else:
        parent[rootB] = rootA
        rank[rootA] += 1
      return True


"""
Trees should stay almost flat...so combined with path compression, find ~ O(1) and union ~ O(1), even for millions of node
Union find always tries: small tree -> attach -> big tree and never big tree -> attach -> small tree
this keeps the depth minimal

When to reach for Union-Find:
If you see these phrases in a LeetCode prompt, ignore BFS/DFS and use Union-Find:
"Find the number of connected components."
"Are these two nodes connected?"
"Detect a cycle in an undirected graph."
"Redundant Connection."
"Earliest moment everyone became friends."
"""