# -*- coding: utf-8 -*-
"""Mini-concepts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FfaeqKEmas6y5ZNWib9jbluI41tOnuyX
"""

arr = [10,2,30,4,66,25]

arr, arr[0], arr[-1], arr[-2]

arr[3] = 99

arr


""" Access/Update : O(1)
"""

# modify without creating a new array - O(1) space

a = [2,3,4,5,6]

def square_in_place(a):
  for i in range(len(a)):
    a[i] = a[i] ** 2

square_in_place(a)

a

array = [1,2,3,6,8,90,44]

# append - O(1)
array.append(4)
array

# insert at index - O(n) ---> shifts everything right
array.insert(1,99)
array

# remove by value - O(n) ---> removes first occurence
array.remove(99)
array

# remove by index - O(n) ---> shifts right
array.pop()
array

array.pop(1)   # removes index 1
array

n = len(array) - 1    # delete range
del array[4:n]
array

# Insert(i, value) and pop(0) are O(n) operations....they shift the whole array, so use deque for fast operations.

# Reversing arrays

array1 = [1,2,3,4,5,6,7]

# in-place reverse - O(n) time, O(1) space
# array1.reverse()
# array1

# new reversed list - O(n) space, O(n) time
# reversed_list = array1[::-1]
# reversed_list

# Manual two-pointer reverse
l, r = 0, len(array1) - 1
while l<r:
  array1[l], array1[r] = array1[r], array1[l]
  l += 1
  r -= 1

array1

# Swapping elements
# Pythonice swap - no temp variables needed - O(1) space and time
array1[2], array1[1] = array1[1], array1[2]
array1

# Iterating forward and backward --> either direction O(n)

# forward
for i in range(len(array1)):
  print(array1[i])

# backward
for i in range(len(array1)-1, -1, -1):
  print(array1[i])

for x in reversed(array1):
  print(x)

# Two pointer array manipulation

# Pattern 1: Opposite ends (two sum sorted, palindrome)
l, r = 0, len(array1) - 1
# while l<r:
#   if condition: l += 1
#   else: r -= 1


array2 = [1, 1, 4, 5, 6, 5, 0]
# Pattern 2: Same direction fast/slow (remove duplicates)
def removeDuplicates(self, array2):
  slow = 0
  for fast in range(len(array2)):
    if array2[fast] != array2[slow]:
      slow += 1
      array2[slow] = array2[fast]
  return slow + 1         # new length

array2

# two separate arrays - merge ---> O(1) time and O(n) space
def merge(a, b):
  result = []
  i, j = 0, 0
  while i < len(a) and j < len(b):
    if a[i] < b[j]:
      result.append(a[i])
      i += 1
    else:
      result.append(b[j])
      j += 1
  result.extend(a[i:]); result.extend(b[j:])
  print(result)

merge(a=[1,2,3,4,5],b=[3,2,4,5,7])

""" Edge cases to always check
"""

def solve(arr):
  # Empty array
  if not arr: return []

  # Single element
  if len(arr) == 1: return arr[0]

  # 3. All duplicates: [1,1,1,1]
  # 4. Already sorted: [1,2,3,4]
  # 5. Reverse sorted: [4,3,2,1]
  # 6. Negative numbers: [-3,-1,0,2]
  # 7. Single pair: [a, b]

  # Most two-pointer bugs hide in cases 6 and 7

