class Solution:
    def subarraySum(self, nums: List[int], k: int) -> int:
        hashMap = {0:1}
        prefixSum = 0
        count = 0
        for i in range(len(nums)):
            prefixSum += nums[i]
            remove = prefixSum - k
            count += hashMap.get(remove, 0)
            hashMap[prefixSum] = hashMap.get(prefixSum,0) + 1
        return count
        
        
    
        """Algorithm Overview                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                      
  Key Insight:                                                                                                                                                                                                                                                                                        
  - If prefixSum[j] - prefixSum[i] = k, then the subarray from i+1 to j sums to k                                                                                                                                                                                                                     
  - Rearranging: prefixSum[i] = prefixSum[j] - k                                                                                                                                                                                                                                                      
  - So for each position, check if (currentPrefixSum - k) exists in our hashmap                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                      
  Code Breakdown                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                      
  hashMap = {0: 1}     # Stores {prefixSum: frequency}                                                                                                                                                                                                                                                
                       # {0: 1} handles subarrays starting from index 0                                                                                                                                                                                                                               
  prefixSum = 0        # Running sum                                                                                                                                                                                                                                                                  
  count = 0            # Number of subarrays found                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                      
  for i in range(len(nums)):                                                                                                                                                                                                                                                                          
      prefixSum += nums[i]              # Update running sum                                                                                                                                                                                                                                          
      remove = prefixSum - k            # What prefix sum do we need?                                                                                                                                                                                                                                 
      count += hashMap.get(remove, 0)   # Add how many times we've seen it                                                                                                                                                                                                                            
      hashMap[prefixSum] = hashMap.get(prefixSum, 0) + 1  # Store current prefix                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                      
  return count                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                      
  Step-by-Step Example: nums = [1, 2, 3], k = 3                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                      
  # Initial: hashMap = {0: 1}, prefixSum = 0, count = 0                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                      
  # ========================================                                                                                                                                                                                                                                                          
  # i = 0, nums[0] = 1                                                                                                                                                                                                                                                                                
  # ========================================                                                                                                                                                                                                                                                          
  prefixSum = 0 + 1 = 1                                                                                                                                                                                                                                                                               
  remove = 1 - 3 = -2                                                                                                                                                                                                                                                                                 
  # Check: Is -2 in hashMap? NO                                                                                                                                                                                                                                                                       
  count += hashMap.get(-2, 0) = 0 + 0 = 0                                                                                                                                                                                                                                                             
  # Store prefix sum 1                                                                                                                                                                                                                                                                                
  hashMap[1] = hashMap.get(1, 0) + 1 = 0 + 1 = 1                                                                                                                                                                                                                                                      
  # hashMap = {0: 1, 1: 1}                                                                                                                                                                                                                                                                            
  State: hashMap = {0: 1, 1: 1}, prefixSum = 1, count = 0                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                      
  # ========================================                                                                                                                                                                                                                                                          
  # i = 1, nums[1] = 2                                                                                                                                                                                                                                                                                
  # ========================================                                                                                                                                                                                                                                                          
  prefixSum = 1 + 2 = 3                                                                                                                                                                                                                                                                               
  remove = 3 - 3 = 0                                                                                                                                                                                                                                                                                  
  # Check: Is 0 in hashMap? YES! (frequency = 1)                                                                                                                                                                                                                                                      
  count += hashMap.get(0, 0) = 0 + 1 = 1  ✓ Found subarray [1,2]                                                                                                                                                                                                                                      
  # Store prefix sum 3                                                                                                                                                                                                                                                                                
  hashMap[3] = hashMap.get(3, 0) + 1 = 0 + 1 = 1                                                                                                                                                                                                                                                      
  # hashMap = {0: 1, 1: 1, 3: 1}                                                                                                                                                                                                                                                                      
  State: hashMap = {0: 1, 1: 1, 3: 1}, prefixSum = 3, count = 1                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                      
  # ========================================                                                                                                                                                                                                                                                          
  # i = 2, nums[2] = 3                                                                                                                                                                                                                                                                                
  # ========================================                                                                                                                                                                                                                                                          
  prefixSum = 3 + 3 = 6                                                                                                                                                                                                                                                                               
  remove = 6 - 3 = 3                                                                                                                                                                                                                                                                                  
  # Check: Is 3 in hashMap? YES! (frequency = 1)                                                                                                                                                                                                                                                      
  count += hashMap.get(3, 0) = 1 + 1 = 2  ✓ Found subarray [3]                                                                                                                                                                                                                                        
  # Store prefix sum 6                                                                                                                                                                                                                                                                                
  hashMap[6] = hashMap.get(6, 0) + 1 = 0 + 1 = 1                                                                                                                                                                                                                                                      
  # hashMap = {0: 1, 1: 1, 3: 1, 6: 1}                                                                                                                                                                                                                                                                
  State: hashMap = {0: 1, 1: 1, 3: 1, 6: 1}, prefixSum = 6, count = 2 
        """
        
        
        """APPROACH: Prefix Sum + HashMap                                                                                                                                                                                                                                                      
       5 +                                                                                                                                                                                                                                                                                            
       6 +        KEY INSIGHT (speak this):                                                                                                                                                                                                                                                           
       7 +        "If we have a prefix sum at position j and we've seen prefix sum (j - k) before,                                                                                                                                                                                                    
       8 +        that means the subarray between those two positions sums to k.                                                                                                                                                                                                                      
       9 +        So for each position, I check if (current prefix sum - k) exists in my hashmap."                                                                                                                                                                                                    
      10 +                                                                                                                                                                                                                                                                                            
      11 +        TIME: O(n) - single pass through array                                                                                                                                                                                                                                              
      12 +        SPACE: O(n) - hashmap stores up to n prefix sums                                                                                                                                                                                                                                    
      13 +                                                                                                                                                                                                                                                                                  
      14 +                                                                                                                                                                                                                                                                                            
      15 +        # Initialize hashmap with {0: 1} to handle subarrays that start from index 0                                                                                                                                                                                                        
      16 +        # For example: if nums=[3] and k=3, we need prefix sum 0 to count this                                                                                                                                                                                                              
      17 +        hashMap = {0: 1}  # {prefix_sum: frequency}                                                                                                                                                                                                                                         
      18 +                                                                                                                                                                                                                                                                                            
      19 +        prefixSum = 0  # Running cumulative sum                                                                                                                                                                                                                                             
      20 +        count = 0      # Number of valid subarrays found                                                                                                                                                                                                                                    
      21 +                                                                                                                                                                                                                                                                                            
      22          for i in range(len(nums)):                                                                                                                                                                                                                                                          
      23 +            # Step 1: Add current element to our running prefix sum                                                                                                                                                                                                                         
      24              prefixSum += nums[i]                                                                                                                                                                                                                                                            
      25 +                                                                                                                                                                                                                                                                                            
      26 +            # Step 2: Calculate what prefix sum we need to have seen before                                                                                                                                                                                                                 
      27 +            # If (prefixSum - remove) = k, then we found a valid subarray                                                                                                                                                                                                                   
      28              remove = prefixSum - k                                                                                                                                                                                                                                                          
      29 +                                                                                                                                                                                                                                                                                            
      30 +            # Step 3: Check how many times we've seen that prefix sum before                                                                                                                                                                                                                
      31 +            # Each occurrence represents one valid subarray ending at current position                                                                                                                                                                                                      
      32              count += hashMap.get(remove, 0)                                                                                                                                                                                                                                                 
      33 -            hashMap[prefixSum] = hashMap.get(prefixSum,0) + 1                                                                                                                                                                                                                               
      33 +                                                                                                                                                                                                                                                                                            
      34 +            # Step 4: Store current prefix sum in hashmap for future iterations                                                                                                                                                                                                             
      35 +            # We use frequency count because same prefix sum can appear multiple times                                                                                                                                                                                                      
      36 +            hashMap[prefixSum] = hashMap.get(prefixSum, 0) + 1                                                                                                                                                                                                                              
      37 +                                                                                                                                                                                                                                                                                            
      38          return count                     
        """