# -*- coding: utf-8 -*-
"""Heap/Priority Queue.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FixUdcS9I47zFLZPh2Mvgqk6F92Z4z1a
"""

# build min heap(heapify)
# Time: O(n), space: O(1)

A = [-4, 1, 5, 3, 8, 11, -2, 1, 9, 0]

# this is how we build a heap

import heapq
heapq.heapify(A)

A

# heap pop (Extract the min)
# time: O(log n) : O(log n) because after the min elements gets extracted, the heap will have to be adjusted

minn = heapq.heappop(A)
A, minn

# heap sort
# time: O(n log n), Sapce: O(n)
# it is possible to have the space complexity as O(1), but its rather complex

import heapq

def heapsort(arr):
  # first make a heap out of the elements
  # create a new list that contains the minimum value of the heap
  # iterate through the length of the array
  # keep on popping the min element in the heap
  # and in the ith position replace it with the min element of the heap

  heapq.heapify(arr)
  n = len(arr)
  new_list = [0] * n
  for i in range(n):
    minn = heapq.heappop(arr)
    new_list[i] = minn

  return new_list

heapsort([1,4,8,7,-2,0,9,3])

# Adding an element to the heap

heapq.heappushpop(A, 3)
A

# peeking the smallest element. the minimum is always gonna be the first element of the array (the root of the heap)
# Time: O(1)

A[0]

# building a heap from scratch : T:O(n log n)
# using heapify would make it O(log n), but sometimes we might have to do this as well

B = [1,5,-2,4,20,8,6,-4]

heap = []
for x in B:
  heapq.heappush(heap, x)
  print(heap, len(heap))

# putting tuples of items in the heap to sort the priority

C = [5, 4, 2, 0, 5, 2, 2, 0, 2, 4, 5, 0, 0, 0]

from collections import Counter

counter = Counter(C)

counter

"""
  For inserting the key, value pair in a heap, we first initialize a heap, and go through each key and value pair in the counter. Then we push each of those elements as a tuple to our heap and then output it.
"""

heap = []

for k, v in counter.items():
  heapq.heappush(heap, (v, k))

heap

"""
Max-heap
  A heap is a min-heap by default....
  There is no exact way to make a max-heap
"""

D = [4,9,1,0,10,44,17,2]
n = len(D)

for i in range(n):
  D[i] = -D[i]

heapq.heapify(D)
D

# maxHeap = -D[0]
# maxHeap

largest = -heapq.heappop(D)
largest

# if you wanna push a value to your max-heap, you have to give an opposite value, the negated value

heapq.heappush(D, -22)    # This inserts 22 into max-heap
D

largest = -heapq.heappop(D)
largest

