# -*- coding: utf-8 -*-
"""LinkedList.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XrU4xRsJfXbk1XBN6nIZ3Zmz5p6HSC5L
"""

""" The Node Structure for a singly linked list
"""

class ListNode:
  def __init__(self, val, next=None):
    self.val = val
    self.next = next

  def __str__(self):
    return str(self.val)

Head = ListNode(1)
A = ListNode(3)
B = ListNode(4)
C = ListNode(7)

Head.next = A
A.next = B
B.next = C

print(Head.val)

# Traverse the list - O(n)

curr = Head

while curr:
  print(curr.val)
  curr = curr.next

# Display a linked list - O(n)

def display(head):
  curr = head
  elements = []
  while curr:
    elements.append(str(curr.val))
    curr = curr.next
  print(' -> '.join(elements))

display(Head)


# ['a, 'b, 'c] -> 'abc' is done by a join

# Seach for a node value (O(n))

def search(head, val):
  curr = head
  while curr:
    if curr.val == val:
      return True
    curr = curr.next
  return False

search(Head, 4)

# Doubly Linked List

class DoublyNode:
  def __init__(self, val, next=None, prev=None):
    self.val = val
    self.next = next
    self.prev = prev

  def __str__(self):
    return str(self.val)

head = tail = DoublyNode(1)
print(tail)

# Display the list - O(n)

def displayDLL(head):
  curr = head
  elements = []
  while curr:
    elements.append(str(curr.val))
    curr = curr.next
    print(' <-> '.join(elements))

displayDLL(tail)

# Insert at beginning - O(n)

def insert_at_beginning(head, tail, val):
  new_node = DoublyNode(val, next=head)
  head.prev = new_node
  return new_node, tail

head, tail = insert_at_beginning(head, tail, 3)
displayDLL(head)

# Insert at end - O(n)

def insert_at_end(head, tail, val):
  new_node = DoublyNode(val, prev=tail)
  tail.next = new_node
  return head, new_node

head, tail = insert_at_end(head, tail, 7)
displayDLL(head)

# Reversing a Linked List

def reverse(head):
  prev, curr = None, head
  while curr:
    nxt = curr.next
    curr.next = prev